### PR TITLE
Allow loading of resources from an unpacked directory.

### PR DESCRIPTION
**Pull request by alxcenz**
This is to facilitate easier development - it's easier to just edit a tilesheet and have the engine load it without having to repack every time during development.

### CODE REVIEW

**Comment by lillian-lemmer** [comment]
For sure, great idea. :) I'll be sure to update the `Resource` class so it can read from zips and directories alike. It is certainly very annoying to have to repack every time. :p

**Comment by alxcenz** [comment]
Already beat you to it. :shipit:

**Comment by lillian-lemmer** [comment]
Oh awesome, I didn't even see that. Thank you so much. I won't be available for programming for a bit (week or so), but I did review your code--excellent stuff! Exactly how I would've done it! <3 Thank you so much for your quality commit. <3 I'll merge in the future. :)

**Comment by lillian-lemmer** [comment]
Seems this issue is resolved. Thanks for your contributions~

**Comment by lillian-lemmer** [comment]
Thank you for your hard work~ <3

**Pull request merged**
