### PR TITLE
Test script force reinstalls

### PR DESCRIPTION
**Pull request by ejmr**

### CODE REVIEW

**Comment by ejmr** [comment]
The second commit in the pull-request can be dropped since 39295fef5fa1b3cb79d9a1a02e90da08c1ce6a4b does the same thing.

**Comment by lillian-lemmer** [comment]
you have my :+1: to merge

**Comment by ejmr** [comment]
Cherry-picked the first commit as d50c4a89b963e850dca4a8b36fda641e557be838 into `develop` and omitted the second.

**Comment by lillian-lemmer** [comment]
:+1:

**Pull request closed without merging**
