### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by bsdjunk**
Fix a typo

### CODE REVIEW

**Comment by alxcenz** [comment]
I don't know how so many people have failed to see that. Thank you!

**Comment by lillian-lemmer** [comment]
Thanks @bsdjunk! @alxcenz did this get merged into develop as well?

**Comment by alxcenz** [comment]
Nope but I'll cherrypick it now. 

-----Original Message-----

**Comment by lillian-lemmer** [comment]
@alxcenz please be careful to merge to the `develop` branch and never directly to master unless you're willing to hotfix + release, though I think nobody will care about us updating the readme. :) Thank you both for your time <3

**Comment by lillian-lemmer** [comment]
ER that's to say that modifying the readme to fix a typo probably isn't a great reason to create a release, so in this instance, creating a hotfix which doesn't create a release isn't the worst thing. But yeah always merge to `develop` first. :) <3 thanks

**Pull request merged**
