### PR TITLE
Anchor multiplication

### PR DESCRIPTION
**Pull request by ejmr**

### CODE REVIEW

**Comment by ejmr** [comment]
`37db06c` did not raise any errors I noticed when run the test suite locally, so if you want to hold off on merging I will look into why it's breaking on the Travis-CI build after I get some sleep.

**Comment by ejmr** [comment]
So the problem with `37db06c` is that it includes some doctests intended to show how certain methods will raise exceptions under certain conditions.  The Python 2.7 build on Travis-CI breaks because it raises somewhat different exceptions, or exceptions with different error messages, than Python 3.  As far as I know there is no way to  rewrite the doctests so that they would account for both types of exceptions.  So the options I see are:

1. Remove the doctests.  I'm not really in favor of this because testing the catching up certain exceptions is important to these changes, specifically because the purpose of the commit is to introduce the use of `NotImplemented` exceptions.

2. Reject `37db06c` on the basis of introducing the `NotImplemented` exceptions for causing the disparity errors between Python 2 and 3 doctests.  I'm also against this because I think using `NotImplemented` is "The Right Thing to Do".

3. Ignore the fact that those tests fail for Python 2.  This would only be ideal if we had a way to tell Python 2 to ignore those doctests, but as far as I know there's no way to do that.

**Comment by lillian-lemmer** [comment]
I think the best solution is to use the inline comment `# doctest: +SKIP` in your doctest.

**Comment by ejmr** [comment]
Thanks, I had forgotten that even existed.  Would it be possible to skip the tests only when running Python 2?

**Comment by lillian-lemmer** [comment]
https://pymotw.com/2/doctest/ seemed more thorough to me than the official docs. I didn't see anything about inline doctest comments that allow you to skip for specific versions of python, though. The best we can do is make the documentation for this issue very apparent, skip the particular tests, test these things in py.test scripts for more fine-tuned-testing control.

**Pull request merged**
